// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TabView10 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_Debug = NULL;
lv_obj_t * ui_Wifi_Status = NULL;
lv_obj_t * ui_PasswordText = NULL;
lv_obj_t * ui_Wifi_List = NULL;
lv_obj_t * ui_Connect1 = NULL;
lv_obj_t * ui_Connect = NULL;
lv_obj_t * ui_Cmd = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_Wifi_state = NULL;
lv_obj_t * ui_disconnect = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_TemperatureText = NULL;
lv_obj_t * ui_HumidityText = NULL;
lv_obj_t * ui_LightText = NULL;
lv_obj_t * ui_TabPage3 = NULL;
// event funtions
void ui_event_PasswordText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_PasswordText);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Connect1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        do_wifi_connect(e);
    }
}

void ui_event_disconnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        do_wifi_disconnect(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView10 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView10, 769);
    lv_obj_set_height(ui_TabView10, 453);
    lv_obj_set_x(ui_TabView10, 4);
    lv_obj_set_y(ui_TabView10, 1);
    lv_obj_set_align(ui_TabView10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView10, "Connect Control");

    ui_Debug = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Debug, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Debug, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Debug, -13);
    lv_obj_set_y(ui_Debug, -170);
    lv_obj_set_align(ui_Debug, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Debug, "Password");

    ui_Wifi_Status = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Wifi_Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi_Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi_Status, -341);
    lv_obj_set_y(ui_Wifi_Status, -92);
    lv_obj_set_align(ui_Wifi_Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifi_Status, "WiFi state");

    ui_PasswordText = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_PasswordText, 276);
    lv_obj_set_height(ui_PasswordText, 64);
    lv_obj_set_x(ui_PasswordText, 190);
    lv_obj_set_y(ui_PasswordText, -157);
    lv_obj_set_align(ui_PasswordText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PasswordText, "Please input password...");

    ui_Wifi_List = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Wifi_List, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi_List, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi_List, -345);
    lv_obj_set_y(ui_Wifi_List, -170);
    lv_obj_set_align(ui_Wifi_List, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifi_List, "Wifi List");

    ui_Connect1 = lv_btn_create(ui_TabPage1);
    lv_obj_set_width(ui_Connect1, 120);
    lv_obj_set_height(ui_Connect1, 50);
    lv_obj_set_x(ui_Connect1, 53);
    lv_obj_set_y(ui_Connect1, -81);
    lv_obj_set_align(ui_Connect1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Connect1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Connect1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Connect1, lv_color_hex(0xE6F3F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Connect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Connect = lv_label_create(ui_Connect1);
    lv_obj_set_width(ui_Connect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Connect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Connect, 5);
    lv_obj_set_y(ui_Connect, 3);
    lv_obj_set_align(ui_Connect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Connect, "Connect");

    ui_Cmd = lv_dropdown_create(ui_TabPage1);
    lv_dropdown_set_options(ui_Cmd, "");
    lv_obj_set_width(ui_Cmd, 195);
    lv_obj_set_height(ui_Cmd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cmd, -192);
    lv_obj_set_y(ui_Cmd, -167);
    lv_obj_set_align(ui_Cmd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cmd, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_TabPage1);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 623);
    lv_obj_set_height(ui_Keyboard1, 269);
    lv_obj_set_x(ui_Keyboard1, 76);
    lv_obj_set_y(ui_Keyboard1, 83);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_Wifi_state = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_Wifi_state, 208);
    lv_obj_set_height(ui_Wifi_state, 55);
    lv_obj_set_x(ui_Wifi_state, -169);
    lv_obj_set_y(ui_Wifi_state, -95);
    lv_obj_set_align(ui_Wifi_state, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Wifi_state, "Wifi State...");

    ui_disconnect = lv_btn_create(ui_TabPage1);
    lv_obj_set_width(ui_disconnect, 120);
    lv_obj_set_height(ui_disconnect, 50);
    lv_obj_set_x(ui_disconnect, 223);
    lv_obj_set_y(ui_disconnect, -80);
    lv_obj_set_align(ui_disconnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_disconnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_disconnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_disconnect);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Disconnect");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView10, "Parameter");

    ui_Label4 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -303);
    lv_obj_set_y(ui_Label4, -126);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Temperature");

    ui_Label5 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -315);
    lv_obj_set_y(ui_Label5, -30);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Humidity");

    ui_Label6 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -325);
    lv_obj_set_y(ui_Label6, 54);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Light");

    ui_TemperatureText = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_TemperatureText, 150);
    lv_obj_set_height(ui_TemperatureText, 40);
    lv_obj_set_x(ui_TemperatureText, -135);
    lv_obj_set_y(ui_TemperatureText, -127);
    lv_obj_set_align(ui_TemperatureText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TemperatureText, "Placeholder...");

    ui_HumidityText = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_HumidityText, 150);
    lv_obj_set_height(ui_HumidityText, 41);
    lv_obj_set_x(ui_HumidityText, -137);
    lv_obj_set_y(ui_HumidityText, -31);
    lv_obj_set_align(ui_HumidityText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_HumidityText, "Placeholder...");

    ui_LightText = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_LightText, 150);
    lv_obj_set_height(ui_LightText, 38);
    lv_obj_set_x(ui_LightText, -136);
    lv_obj_set_y(ui_LightText, 55);
    lv_obj_set_align(ui_LightText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_LightText, "Placeholder...");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView10, "Adjust Control");

    lv_obj_add_event_cb(ui_PasswordText, ui_event_PasswordText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Connect1, ui_event_Connect1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_PasswordText);
    lv_obj_add_event_cb(ui_disconnect, ui_event_disconnect, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TabView10 = NULL;
    ui_TabPage1 = NULL;
    ui_Debug = NULL;
    ui_Wifi_Status = NULL;
    ui_PasswordText = NULL;
    ui_Wifi_List = NULL;
    ui_Connect1 = NULL;
    ui_Connect = NULL;
    ui_Cmd = NULL;
    ui_Keyboard1 = NULL;
    ui_Wifi_state = NULL;
    ui_disconnect = NULL;
    ui_Label7 = NULL;
    ui_TabPage2 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_TemperatureText = NULL;
    ui_HumidityText = NULL;
    ui_LightText = NULL;
    ui_TabPage3 = NULL;

}
