// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView10;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_RefreshButton1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Debug;
extern lv_obj_t * ui_Wifi_Status;
extern void ui_event_PasswordText(lv_event_t * e);
extern lv_obj_t * ui_PasswordText;
extern lv_obj_t * ui_WifiLabel;
extern void ui_event_Connect1(lv_event_t * e);
extern lv_obj_t * ui_Connect1;
extern lv_obj_t * ui_Connect;
extern void ui_event_SendCmd(lv_event_t * e);
extern lv_obj_t * ui_SendCmd;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_WifiList;
extern lv_obj_t * ui_Wifi_state;
extern void ui_event_disconnect(lv_event_t * e);
extern lv_obj_t * ui_disconnect;
extern lv_obj_t * ui_Label7;
extern void ui_event_SendText(lv_event_t * e);
extern lv_obj_t * ui_SendText;
extern lv_obj_t * ui_Rxstr;
extern lv_obj_t * ui_Rxtext;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_ServerLabel;
extern lv_obj_t * ui_ServerArea2;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_TemperatureText;
extern lv_obj_t * ui_HumidityText;
extern lv_obj_t * ui_LightText;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_TempSlider;
extern lv_obj_t * ui_HumiditySlider;
extern lv_obj_t * ui_LightSlider;
extern lv_obj_t * ui_humidityLabel;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_LightLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

