// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView10;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Uart3TX;
extern lv_obj_t * ui_Debug;
extern lv_obj_t * ui_Uart3RX;
extern lv_obj_t * ui_GDBText;
extern void ui_event_SendText(lv_event_t * e);
extern lv_obj_t * ui_SendText;
extern lv_obj_t * ui_ReceiText;
extern lv_obj_t * ui_Cmd;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_TabPage3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

