// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TabView10 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_GDBText = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_TextArea4 = NULL;
lv_obj_t * ui_TextArea5 = NULL;
lv_obj_t * ui_TabPage3 = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView10 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView10, 769);
    lv_obj_set_height(ui_TabView10, 453);
    lv_obj_set_x(ui_TabView10, 2);
    lv_obj_set_y(ui_TabView10, 1);
    lv_obj_set_align(ui_TabView10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView10, "Connect Control");

    ui_Label1 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -317);
    lv_obj_set_y(ui_Label1, -19);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "USART3 Send");

    ui_Label2 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -327);
    lv_obj_set_y(ui_Label2, -118);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "DBG");

    ui_Label3 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -306);
    lv_obj_set_y(ui_Label3, 44);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "USART3 Receive");

    ui_GDBText = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_GDBText, 392);
    lv_obj_set_height(ui_GDBText, 70);
    lv_obj_set_x(ui_GDBText, -36);
    lv_obj_set_y(ui_GDBText, -118);
    lv_obj_set_align(ui_GDBText, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_GDBText, "GDB");
    lv_textarea_set_placeholder_text(ui_GDBText, "Placeholder...");

    ui_TextArea1 = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_TextArea1, 397);
    lv_obj_set_height(ui_TextArea1, 42);
    lv_obj_set_x(ui_TextArea1, -26);
    lv_obj_set_y(ui_TextArea1, -24);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "hello");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_TextArea2 = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_TextArea2, 396);
    lv_obj_set_height(ui_TextArea2, 42);
    lv_obj_set_x(ui_TextArea2, -26);
    lv_obj_set_y(ui_TextArea2, 35);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea2, "hello1");
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView10, "Parameter");

    ui_Label4 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -303);
    lv_obj_set_y(ui_Label4, -126);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Temperature");

    ui_Label5 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -315);
    lv_obj_set_y(ui_Label5, -30);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Humidity");

    ui_Label6 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -325);
    lv_obj_set_y(ui_Label6, 54);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Light");

    ui_TextArea3 = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_TextArea3, 150);
    lv_obj_set_height(ui_TextArea3, 40);
    lv_obj_set_x(ui_TextArea3, -135);
    lv_obj_set_y(ui_TextArea3, -127);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");

    ui_TextArea4 = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_TextArea4, 150);
    lv_obj_set_height(ui_TextArea4, 41);
    lv_obj_set_x(ui_TextArea4, -137);
    lv_obj_set_y(ui_TextArea4, -31);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");

    ui_TextArea5 = lv_textarea_create(ui_TabPage2);
    lv_obj_set_width(ui_TextArea5, 150);
    lv_obj_set_height(ui_TextArea5, 38);
    lv_obj_set_x(ui_TextArea5, -136);
    lv_obj_set_y(ui_TextArea5, 55);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea5, "Placeholder...");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView10, "Adjust Control");

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TabView10 = NULL;
    ui_TabPage1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_GDBText = NULL;
    ui_TextArea1 = NULL;
    ui_TextArea2 = NULL;
    ui_TabPage2 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_TextArea3 = NULL;
    ui_TextArea4 = NULL;
    ui_TextArea5 = NULL;
    ui_TabPage3 = NULL;

}
