// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "usart.h"
#include "led.h"
#include "stdio.h"
#include "string.h"

/* WiFi control functions - SquareLine preserves custom code below */

#include "ui_custom.h"

void do_wifi_connect(lv_event_t * e)
{
    (void)e;
    char ssid[64] = {0};
    char password[64] = {0};
    char cmd_buf[256] = {0};

    lv_dropdown_get_selected_str(ui_Cmd, ssid, sizeof(ssid));
    const char *pass_text = lv_textarea_get_text(ui_PasswordText);
    strncpy(password, pass_text, sizeof(password) - 1);

    snprintf(cmd_buf, sizeof(cmd_buf), "WIFI_CONNECT:%s,%s\n", ssid, password);
    Send_AT_Command(cmd_buf);

    update_wifi_status("Connecting...");
    LED1_Green_TOGGLE();
}

void do_wifi_disconnect(lv_event_t * e)
{
    (void)e;
    Send_AT_Command("WIFI_DISCONNECT\n");
    update_wifi_status("Disconnected");
    LED1_Green_TOGGLE();
}
