// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "usart.h"
#include "led.h"
#include "stdio.h"
#include "string.h"

/* WiFi control functions - SquareLine preserves custom code below */

#include "ui_custom.h"

void do_wifi_connect(lv_event_t * e)
{
    (void)e;
    char ssid[64] = {0};
    char password[64] = {0};
    char cmd_buf[256] = {0};
    char display_buf[128] = {0};

    lv_dropdown_get_selected_str(ui_WifiList, ssid, sizeof(ssid));
    const char *pass_text = lv_textarea_get_text(ui_PasswordText);
    if (pass_text != NULL) {
        strncpy(password, pass_text, sizeof(password) - 1);
    }

    /* 过滤密码末尾的换行回车和空格（虚拟键盘容易带入） */
    size_t pass_len = strlen(password);
    while (pass_len > 0 && (password[pass_len - 1] == '\r' ||
                            password[pass_len - 1] == '\n' ||
                            password[pass_len - 1] == ' ')) {
        password[--pass_len] = '\0';
    }

    /* 参数校验 */
    if (ssid[0] == '\0') {
        update_wifi_status("Error: Select WiFi first");
        update_uart_rx_display("[Error] No WiFi selected, please scan and pick one.\n");
        return;
    }
    if (password[0] == '\0') {
        update_wifi_status("Error: Password empty");
        update_uart_rx_display("[Error] Password is empty.\n");
        return;
    }

    snprintf(cmd_buf, sizeof(cmd_buf), "WIFI_CONNECT:%s,%s", ssid, password);
    Send_AT_Command(cmd_buf);

    /* 调试回显：把发送的命令显示在 Rxtext（密码脱敏） */
    snprintf(display_buf, sizeof(display_buf),
             "[CMD] WIFI_CONNECT:%s,****** (len=%d)\n", ssid, (int)pass_len);
    update_uart_rx_display(display_buf);

    update_wifi_status("Connecting...");
    LED1_Green_TOGGLE();
}

void do_wifi_disconnect(lv_event_t * e)
{
    (void)e;
    Send_AT_Command("WIFI_DISCONNECT");
    update_wifi_status("Disconnected");
    LED1_Green_TOGGLE();
}

void Send_cmd(lv_event_t * e)
{
    (void)e;
    const char *cmd_text = lv_textarea_get_text(ui_SendText);
    if (cmd_text != NULL && cmd_text[0] != '\0') {
        Send_AT_Command(cmd_text);
    }
}
void do_wifi_refresh(lv_event_t * e)
{
    (void)e;
    wifi_scan_start();
    LED1_Green_TOGGLE();
}

void keyboard_draggble(lv_event_t * e)
{
    (void)e;
}
